[package]
name = "longbridge-lite"
version = "0.5.1"
edition = "2024"
publish = false

[dependencies]
gpui-shell = { git = "https://github.com/longbridge/gpui-kit" }
gpui-kit = { git = "https://github.com/longbridge/gpui-kit", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
gpui-kit = { git = "https://github.com/longbridge/gpui-kit", default-features = false, features = ["test-support"] }

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-base = { opt-level = 3 }
gpui-pre-platform = { opt-level = 3 }
gpui-shell = { opt-level = 3 }
rquickjs = { opt-level = 3 }
